# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Interferometer.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QDoubleSpinBox, QLabel,
    QPushButton, QRadioButton, QSizePolicy, QSlider,
    QSpinBox, QTabWidget, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(600, 500)
        icon = QIcon()
        icon.addFile(u"D:/BlueStacks/ico/\u9010\u706b\u5341\u4e09\u82f1\u6840/Kosma.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        Form.setWindowIcon(icon)
        self.radioButton_2 = QRadioButton(Form)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(130, 20, 95, 20))
        self.radioButton = QRadioButton(Form)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(40, 20, 95, 20))
        self.radioButton.setChecked(True)
        self.checkBox = QCheckBox(Form)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(470, 20, 79, 20))
        self.tabWidget = QTabWidget(Form)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 350, 600, 150))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.pushButton_1 = QPushButton(self.tab)
        self.pushButton_1.setObjectName(u"pushButton_1")
        self.pushButton_1.setGeometry(QRect(350, 90, 75, 27))
        self.label_11 = QLabel(self.tab)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(220, 50, 31, 22))
        self.doubleSpinBox_13 = QDoubleSpinBox(self.tab)
        self.doubleSpinBox_13.setObjectName(u"doubleSpinBox_13")
        self.doubleSpinBox_13.setGeometry(QRect(420, 50, 110, 22))
        self.doubleSpinBox_13.setMinimum(0.010000000000000)
        self.doubleSpinBox_13.setMaximum(1000.000000000000000)
        self.doubleSpinBox_13.setValue(10.000000000000000)
        self.label_12 = QLabel(self.tab)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(5, 10, 54, 20))
        self.doubleSpinBox_14 = QDoubleSpinBox(self.tab)
        self.doubleSpinBox_14.setObjectName(u"doubleSpinBox_14")
        self.doubleSpinBox_14.setGeometry(QRect(180, 90, 110, 25))
        self.doubleSpinBox_14.setMinimum(390.000000000000000)
        self.doubleSpinBox_14.setMaximum(760.000000000000000)
        self.doubleSpinBox_14.setValue(700.000000000000000)
        self.horizontalSlider_1 = QSlider(self.tab)
        self.horizontalSlider_1.setObjectName(u"horizontalSlider_1")
        self.horizontalSlider_1.setGeometry(QRect(73, 10, 450, 20))
        self.horizontalSlider_1.setMinimum(390)
        self.horizontalSlider_1.setMaximum(760)
        self.horizontalSlider_1.setValue(700)
        self.horizontalSlider_1.setOrientation(Qt.Horizontal)
        self.doubleSpinBox_12 = QDoubleSpinBox(self.tab)
        self.doubleSpinBox_12.setObjectName(u"doubleSpinBox_12")
        self.doubleSpinBox_12.setGeometry(QRect(250, 50, 110, 22))
        self.doubleSpinBox_12.setMaximum(1000.000000000000000)
        self.doubleSpinBox_12.setValue(760.000000000000000)
        self.doubleSpinBox_11 = QDoubleSpinBox(self.tab)
        self.doubleSpinBox_11.setObjectName(u"doubleSpinBox_11")
        self.doubleSpinBox_11.setGeometry(QRect(80, 50, 110, 22))
        self.doubleSpinBox_11.setMinimum(0.000000000000000)
        self.doubleSpinBox_11.setMaximum(1000.000000000000000)
        self.doubleSpinBox_11.setValue(390.000000000000000)
        self.label_13 = QLabel(self.tab)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(390, 50, 31, 22))
        self.label_14 = QLabel(self.tab)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(150, 90, 21, 25))
        self.label_15 = QLabel(self.tab)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(50, 50, 31, 22))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_8 = QLabel(self.tab_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(5, 10, 61, 20))
        self.pushButton_2 = QPushButton(self.tab_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(350, 90, 75, 27))
        self.label_10 = QLabel(self.tab_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(420, 50, 31, 22))
        self.label_7 = QLabel(self.tab_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(250, 50, 31, 22))
        self.label_9 = QLabel(self.tab_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(80, 50, 31, 22))
        self.label_6 = QLabel(self.tab_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(170, 90, 21, 25))
        self.horizontalSlider_2 = QSlider(self.tab_2)
        self.horizontalSlider_2.setObjectName(u"horizontalSlider_2")
        self.horizontalSlider_2.setGeometry(QRect(73, 10, 450, 20))
        self.horizontalSlider_2.setMinimum(2)
        self.horizontalSlider_2.setMaximum(30)
        self.horizontalSlider_2.setOrientation(Qt.Horizontal)
        self.spinBox_21 = QSpinBox(self.tab_2)
        self.spinBox_21.setObjectName(u"spinBox_21")
        self.spinBox_21.setGeometry(QRect(110, 50, 42, 22))
        self.spinBox_21.setMinimum(2)
        self.spinBox_21.setMaximum(100)
        self.spinBox_21.setValue(2)
        self.spinBox_22 = QSpinBox(self.tab_2)
        self.spinBox_22.setObjectName(u"spinBox_22")
        self.spinBox_22.setGeometry(QRect(280, 50, 42, 22))
        self.spinBox_22.setMinimum(2)
        self.spinBox_22.setMaximum(100)
        self.spinBox_22.setValue(30)
        self.spinBox_22.setDisplayIntegerBase(10)
        self.spinBox_23 = QSpinBox(self.tab_2)
        self.spinBox_23.setObjectName(u"spinBox_23")
        self.spinBox_23.setGeometry(QRect(450, 50, 42, 22))
        self.spinBox_23.setMinimum(1)
        self.spinBox_24 = QSpinBox(self.tab_2)
        self.spinBox_24.setObjectName(u"spinBox_24")
        self.spinBox_24.setGeometry(QRect(190, 90, 42, 22))
        self.spinBox_24.setMinimum(2)
        self.spinBox_24.setMaximum(30)
        self.spinBox_24.setValue(2)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.pushButton_3 = QPushButton(self.tab_3)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(350, 90, 75, 27))
        self.label_16 = QLabel(self.tab_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(250, 50, 31, 22))
        self.doubleSpinBox_33 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_33.setObjectName(u"doubleSpinBox_33")
        self.doubleSpinBox_33.setGeometry(QRect(450, 50, 62, 22))
        self.doubleSpinBox_33.setValue(0.100000000000000)
        self.label_17 = QLabel(self.tab_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(5, 10, 71, 20))
        self.doubleSpinBox_34 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_34.setObjectName(u"doubleSpinBox_34")
        self.doubleSpinBox_34.setGeometry(QRect(190, 90, 65, 25))
        self.doubleSpinBox_34.setMinimum(0.050000000000000)
        self.doubleSpinBox_34.setMaximum(8.000000000000000)
        self.doubleSpinBox_34.setValue(2.000000000000000)
        self.horizontalSlider_3 = QSlider(self.tab_3)
        self.horizontalSlider_3.setObjectName(u"horizontalSlider_3")
        self.horizontalSlider_3.setGeometry(QRect(73, 10, 450, 20))
        self.horizontalSlider_3.setMinimum(5)
        self.horizontalSlider_3.setMaximum(800)
        self.horizontalSlider_3.setSingleStep(100)
        self.horizontalSlider_3.setValue(200)
        self.horizontalSlider_3.setOrientation(Qt.Horizontal)
        self.doubleSpinBox_32 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_32.setObjectName(u"doubleSpinBox_32")
        self.doubleSpinBox_32.setGeometry(QRect(280, 50, 62, 22))
        self.doubleSpinBox_32.setValue(8.000000000000000)
        self.doubleSpinBox_31 = QDoubleSpinBox(self.tab_3)
        self.doubleSpinBox_31.setObjectName(u"doubleSpinBox_31")
        self.doubleSpinBox_31.setGeometry(QRect(110, 50, 62, 22))
        self.doubleSpinBox_31.setValue(0.050000000000000)
        self.label_18 = QLabel(self.tab_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(420, 50, 31, 22))
        self.label_19 = QLabel(self.tab_3)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(170, 90, 21, 25))
        self.label_20 = QLabel(self.tab_3)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(80, 50, 31, 22))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.pushButton_4 = QPushButton(self.tab_4)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(350, 90, 75, 27))
        self.label_21 = QLabel(self.tab_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(250, 50, 31, 22))
        self.doubleSpinBox_43 = QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_43.setObjectName(u"doubleSpinBox_43")
        self.doubleSpinBox_43.setGeometry(QRect(450, 50, 62, 22))
        self.doubleSpinBox_43.setValue(0.500000000000000)
        self.label_22 = QLabel(self.tab_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(5, 10, 54, 20))
        self.doubleSpinBox_44 = QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_44.setObjectName(u"doubleSpinBox_44")
        self.doubleSpinBox_44.setGeometry(QRect(190, 90, 65, 25))
        self.doubleSpinBox_44.setMinimum(0.100000000000000)
        self.doubleSpinBox_44.setMaximum(15.000000000000000)
        self.doubleSpinBox_44.setValue(1.000000000000000)
        self.horizontalSlider_4 = QSlider(self.tab_4)
        self.horizontalSlider_4.setObjectName(u"horizontalSlider_4")
        self.horizontalSlider_4.setGeometry(QRect(73, 10, 450, 20))
        self.horizontalSlider_4.setMinimum(10)
        self.horizontalSlider_4.setMaximum(1500)
        self.horizontalSlider_4.setSingleStep(100)
        self.horizontalSlider_4.setValue(100)
        self.horizontalSlider_4.setOrientation(Qt.Horizontal)
        self.horizontalSlider_4.setTickPosition(QSlider.NoTicks)
        self.doubleSpinBox_42 = QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_42.setObjectName(u"doubleSpinBox_42")
        self.doubleSpinBox_42.setGeometry(QRect(280, 50, 62, 22))
        self.doubleSpinBox_42.setValue(15.000000000000000)
        self.doubleSpinBox_41 = QDoubleSpinBox(self.tab_4)
        self.doubleSpinBox_41.setObjectName(u"doubleSpinBox_41")
        self.doubleSpinBox_41.setGeometry(QRect(110, 50, 62, 22))
        self.doubleSpinBox_41.setValue(0.100000000000000)
        self.label_23 = QLabel(self.tab_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(420, 50, 31, 22))
        self.label_24 = QLabel(self.tab_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(170, 90, 21, 25))
        self.label_25 = QLabel(self.tab_4)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(80, 50, 31, 22))
        self.tabWidget.addTab(self.tab_4, "")
        self.pushButton_stop = QPushButton(Form)
        self.pushButton_stop.setObjectName(u"pushButton_stop")
        self.pushButton_stop.setGeometry(QRect(290, 15, 80, 30))
        self.pushButton_glimmer = QPushButton(Form)
        self.pushButton_glimmer.setObjectName(u"pushButton_glimmer")
        self.pushButton_glimmer.setGeometry(QRect(380, 15, 80, 30))

        self.retranslateUi(Form)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Interferometer", None))
#if QT_CONFIG(tooltip)
        self.radioButton_2.setToolTip(QCoreApplication.translate("Form", u"\u5efa\u8bae\u5728\u5149\u7ebf\u8f83\u5c11\u65f6\u4f7f\u7528", None))
#endif // QT_CONFIG(tooltip)
        self.radioButton_2.setText(QCoreApplication.translate("Form", u"\u5149\u6ce2\u5f62\u5f0f", None))
        self.radioButton.setText(QCoreApplication.translate("Form", u"\u5149\u7ebf\u5f62\u5f0f", None))
        self.checkBox.setText(QCoreApplication.translate("Form", u"\u663e\u793a\u51fd\u6570", None))
        self.pushButton_1.setText(QCoreApplication.translate("Form", u"\u81ea\u52a8\u9012\u589e", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"\u4e0a\u9650", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"\u6ce2\u957f/nm", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"\u6b65\u957f", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"\u503c", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"\u4e0b\u9650", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Form", u"\u6ce2\u957f", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"\u7f1d\u6570\u91cf/\u4e2a", None))
        self.pushButton_2.setText(QCoreApplication.translate("Form", u"\u81ea\u52a8\u9012\u589e", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"\u6b65\u957f", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"\u4e0a\u9650", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"\u4e0b\u9650", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"\u503c", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Form", u"\u7f1d\u6570\u91cf", None))
        self.pushButton_3.setText(QCoreApplication.translate("Form", u"\u81ea\u52a8\u9012\u589e", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"\u4e0a\u9650", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"\u7f1d\u95f4\u8ddd/mm", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"\u6b65\u957f", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"\u503c", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"\u4e0b\u9650", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Form", u"\u7f1d\u95f4\u8ddd", None))
        self.pushButton_4.setText(QCoreApplication.translate("Form", u"\u81ea\u52a8\u9012\u589e", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"\u4e0a\u9650", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"\u7f1d\u5c4f\u8ddd/m", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"\u6b65\u957f", None))
        self.label_24.setText(QCoreApplication.translate("Form", u"\u503c", None))
        self.label_25.setText(QCoreApplication.translate("Form", u"\u4e0b\u9650", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("Form", u"\u7f1d\u5c4f\u8ddd", None))
        self.pushButton_stop.setText(QCoreApplication.translate("Form", u"\u505c\u6b62\u9012\u589e", None))
        self.pushButton_glimmer.setText(QCoreApplication.translate("Form", u"\u6807\u51c6\u5149\u5f3a", None))
    # retranslateUi

